import { BlogListingProps } from "@/components/utilities/BlogListing";

export const blogCategories: BlogListingProps[] = [
    {
        category: 'All',
        items: []
    },
    {
        category: 'Quantum Computing',
        items: [
            {
                id: 1,
                author: "Sarah Ethicist",
                category: "AI Ethics",
                date: "November 25, 2023",
                title: "The Ethical Dilemmas of AI",
                description: "A deep dive into ethical challenges posed by AI, including bias, privacy, and transparency.",
                likes: "52k",
                comments: 472,
                shares: 187,
                avatar: "https://randomuser.me/api/portraits/women/2.jpg",
            },
            {
                id: 2,
                author: "John Techson",
                category: "Quantum Computing",
                date: "October 15, 2023",
                title: "The Quantum Leap in Computing",
                description: "Explore the revolution in quantum computing, its applications, and its potential impact on various industries.",
                likes: "24.5k",
                comments: 50,
                shares: 20,
                avatar: "https://randomuser.me/api/portraits/men/5.jpg",
            },
            {
                id: 3,
                author: "Astronomer X",
                category: "Space Exploration",
                date: "December 20, 2023",
                title: "The Mars Colonization Challenge",
                description: "Exploring the technical and logistical challenges of human colonization on Mars.",
                likes: "20k",
                comments: 61,
                shares: 17,
                avatar: "https://randomuser.me/api/portraits/men/6.jpg",
            },
        ]
    },
    {
        category: 'AI Ethics',
        items: [
            {
                id: 1,
                author: "Astronomer X",
                category: "Space Exploration",
                date: "December 10, 2023",
                title: "The Mars Colonization Challenge",
                description: "Exploring the technical and logistical challenges of human colonization on Mars.",
                likes: "20k",
                comments: 31,
                shares: 12,
                avatar: "https://randomuser.me/api/portraits/men/7.jpg",
            },
            {
                id: 2,
                author: "John Techson",
                category: "Quantum Computing",
                date: "October 15, 2023",
                title: "The Quantum Leap in Computing",
                description: "Explore the revolution in quantum computing, its applications, and its potential impact on various industries.",
                likes: "24.5k",
                comments: 50,
                shares: 20,
                avatar: "https://randomuser.me/api/portraits/men/8.jpg",
            },
            {
                id: 3,
                author: "Sarah Ethicist",
                category: "AI Ethics",
                date: "November 5, 2023",
                title: "The Ethical Dilemmas of AI",
                description: "A deep dive into ethical challenges posed by AI, including bias, privacy, and transparency.",
                likes: "32k",
                comments: 72,
                shares: 18,
                avatar: "https://randomuser.me/api/portraits/women/9.jpg",
            }
        ]
    },
    {
        category: 'Space Exploration',
        items: [
            {
                id: 1,
                author: "John Techson",
                category: "Quantum Computing",
                date: "October 15, 2023",
                title: "The Quantum Leap in Computing",
                description: "Explore the revolution in quantum computing, its applications, and its potential impact on various industries.",
                likes: "24.5k",
                comments: 50,
                shares: 20,
                avatar: "https://randomuser.me/api/portraits/men/10.jpg",
            },
            {
                id: 2,
                author: "Sarah Ethicist",
                category: "AI Ethics",
                date: "November 5, 2023",
                title: "The Ethical Dilemmas of AI",
                description: "A deep dive into ethical challenges posed by AI, including bias, privacy, and transparency.",
                likes: "32k",
                comments: 72,
                shares: 18,
                avatar: "https://randomuser.me/api/portraits/women/11.jpg",
            },
            {
                id: 3,
                author: "Astronomer X",
                category: "Space Exploration",
                date: "December 10, 2023",
                title: "The Mars Colonization Challenge",
                description: "Exploring the technical and logistical challenges of human colonization on Mars.",
                likes: "20k",
                comments: 31,
                shares: 12,
                avatar: "https://randomuser.me/api/portraits/men/12.jpg",
            },
        ]
    },
    {
        category: 'Biotechnology',
        items: [
            {
                id: 1,
                author: "John Techson",
                category: "Quantum Computing",
                date: "October 15, 2023",
                title: "The Quantum Leap in Computing",
                description: "Explore the revolution in quantum computing, its applications, and its potential impact on various industries.",
                likes: "24.5k",
                comments: 50,
                shares: 20,
                avatar: "https://randomuser.me/api/portraits/men/13.jpg",
            },
            {
                id: 2,
                author: "Sarah Ethicist",
                category: "AI Ethics",
                date: "November 5, 2023",
                title: "The Ethical Dilemmas of AI",
                description: "A deep dive into ethical challenges posed by AI, including bias, privacy, and transparency.",
                likes: "32k",
                comments: 72,
                shares: 18,
                avatar: "https://randomuser.me/api/portraits/women/14.jpg",
            },
            {
                id: 3,
                author: "Astronomer X",
                category: "Space Exploration",
                date: "December 10, 2023",
                title: "The Mars Colonization Challenge",
                description: "Exploring the technical and logistical challenges of human colonization on Mars.",
                likes: "20k",
                comments: 31,
                shares: 12,
                avatar: "https://randomuser.me/api/portraits/men/15.jpg",
            },
        ]
    },
    {
        category: 'Renewable Energy',
        items: [
            {
                id: 1,
                author: "John Techson",
                category: "Quantum Computing",
                date: "October 15, 2023",
                title: "The Quantum Leap in Computing",
                description: "Explore the revolution in quantum computing, its applications, and its potential impact on various industries.",
                likes: "24.5k",
                comments: 50,
                shares: 20,
                avatar: "https://randomuser.me/api/portraits/men/16.jpg",
            },
            {
                id: 2,
                author: "Sarah Ethicist",
                category: "AI Ethics",
                date: "November 5, 2023",
                title: "The Ethical Dilemmas of AI",
                description: "A deep dive into ethical challenges posed by AI, including bias, privacy, and transparency.",
                likes: "32k",
                comments: 72,
                shares: 18,
                avatar: "https://randomuser.me/api/portraits/women/17.jpg",
            },
            {
                id: 3,
                author: "Astronomer X",
                category: "Space Exploration",
                date: "December 10, 2023",
                title: "The Mars Colonization Challenge",
                description: "Exploring the technical and logistical challenges of human colonization on Mars.",
                likes: "20k",
                comments: 31,
                shares: 12,
                avatar: "https://randomuser.me/api/portraits/men/18.jpg",
            },
        ]
    },

]